version: '3.8'

services:
  parser:
    build: .
    container_name: tv-movies-parser
    ports:
      - "5000:5000"
    volumes:
      # Синхронизируем текущую папку с папкой /app внутри контейнера
      - .:/app
    env_file:
      - .env.local
    depends_on:
      - ollama
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data: